# Generated by Django 5.0.6 on 2026-03-16 11:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupos_Agentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupos_Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets_Colas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets_Respuestas_Automaticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets_Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Agentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('nombre_usuario', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(default=None, max_length=200)),
                ('ultima_conexion', models.DateTimeField(default=datetime.datetime.now)),
                ('usuario', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='agente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('nombre_usuario', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Direccion', models.CharField(default=None, max_length=200)),
                ('usuario', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agentes_Por_Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikects_app.agentes')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikects_app.grupos_agentes')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('cerrado_fecha', models.DateTimeField(blank=True, null=True)),
                ('Direccion', models.CharField(default=None, max_length=200)),
                ('descripcion_solucion', models.TextField(blank=True, null=True)),
                ('cerrado_por_agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cerrado_por_agente', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cola_perteneciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikects_app.tickets_colas')),
                ('servicio_perteneciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikects_app.tickets_servicios')),
            ],
        ),
        migrations.CreateModel(
            name='ReasignacionTikects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reasignacion', models.DateTimeField(auto_now_add=True)),
                ('agente_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasignaciones_anterior', to='tikects_app.agentes')),
                ('agente_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasignaciones_nuevo', to='tikects_app.agentes')),
                ('tikect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikects_app.tickets')),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_notificacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikects_app.agentes')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tikect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikects_app.tickets')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionTikects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_reasignacion', models.IntegerField(blank=True, null=True)),
                ('agente_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agente_actual', to='tikects_app.agentes')),
                ('agente_reasignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agente_reasignacion', to='tikects_app.agentes')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikects_app.tickets_servicios')),
            ],
        ),
    ]
