# Generated by Django 6.0.3 on 2026-03-25 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteGenerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_reasignacion', models.IntegerField(blank=True, help_text='Tiempo en minutos', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('agente_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_asignados', to='tikects_app.agentes')),
                ('agente_reasignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_reasignacion', to='tikects_app.agentes')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentes_genericos', to='tikects_app.tickets_servicios')),
            ],
        ),
    ]
