# Generated by Django 5.0.6 on 2026-03-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gerencias',
            new_name='Direcciones',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='gerencia',
            new_name='Direccion',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='gerencia',
            new_name='Direccion',
        ),
    ]
